use super::descriptor::ControlDescriptor;
use super::id::ControlId;

/// Single declarative registry of interactive control descriptors.
pub const DESCRIPTORS: [ControlDescriptor; 39] = [
    ControlDescriptor {
        id: ControlId::OutputsSink,
        probe_name: ControlId::OutputsSink.probe_name(),
        eyebrow: "OUTPUTS",
        label: "Outputs row sinks",
        summary: Some("Switch active video output destinations"),
        hotkey: None,
        operation_title: Some("Route outputs"),
        action: Some("Click to toggle"),
        mcp_policy: Some("route_output"),
    },
    ControlDescriptor {
        id: ControlId::AudioIn,
        probe_name: ControlId::AudioIn.probe_name(),
        eyebrow: "TRANSPORT",
        label: "Audio-in pill",
        summary: Some("Select audio input device for tempo tracking"),
        hotkey: None,
        operation_title: Some("Attach a beat source"),
        action: Some("Click to select"),
        mcp_policy: Some("set_audio_in"),
    },
    ControlDescriptor {
        id: ControlId::Tracker,
        probe_name: ControlId::Tracker.probe_name(),
        eyebrow: "TRANSPORT",
        label: "Tracker group",
        summary: Some("Tap tempo and clock phase adjustments"),
        hotkey: Some("b"),
        operation_title: Some("Tap the beat"),
        action: Some("Click / Tap"),
        mcp_policy: Some("tap_tempo"),
    },
    ControlDescriptor {
        id: ControlId::TransportLearn,
        probe_name: ControlId::TransportLearn.probe_name(),
        eyebrow: "TRANSPORT",
        label: "Transport learn pill",
        summary: Some("Arm MIDI learn mode for live parameter mapping"),
        hotkey: None,
        operation_title: None,
        action: Some("Click to arm"),
        mcp_policy: None,
    },
    ControlDescriptor {
        id: ControlId::TransportMap,
        probe_name: ControlId::TransportMap.probe_name(),
        eyebrow: "TRANSPORT",
        label: "Transport map pill",
        summary: Some("Active hardware MIDI controller mapping profile"),
        hotkey: None,
        operation_title: None,
        action: Some("Click to open"),
        mcp_policy: None,
    },
    ControlDescriptor {
        id: ControlId::Arrangement,
        probe_name: ControlId::Arrangement.probe_name(),
        eyebrow: "TRANSPORT",
        label: "Arrangement pill",
        summary: Some("Console panel layout and arrangement preset"),
        hotkey: Some("r"),
        operation_title: Some("Reset the arrangement"),
        action: Some("Click to reset"),
        mcp_policy: Some("reset_arrangement"),
    },
    ControlDescriptor {
        id: ControlId::Look,
        probe_name: ControlId::Look.probe_name(),
        eyebrow: "TRANSPORT",
        label: "Look group",
        summary: Some("Master tone mapping operator and exposure trim"),
        hotkey: None,
        operation_title: Some("Tone map"),
        action: Some("Click to cycle"),
        mcp_policy: Some("set_look"),
    },
    ControlDescriptor {
        id: ControlId::TransportRec,
        probe_name: ControlId::TransportRec.probe_name(),
        eyebrow: "TRANSPORT",
        label: "Transport rec pill",
        summary: Some("Live session journal recording toggle"),
        hotkey: None,
        operation_title: Some("Record session"),
        action: Some("Click to record"),
        mcp_policy: Some("record_session"),
    },
    ControlDescriptor {
        id: ControlId::TransportTempo,
        probe_name: ControlId::TransportTempo.probe_name(),
        eyebrow: "TRANSPORT",
        label: "Transport tempo figure",
        summary: Some("Master beat clock tempo and tracking grid"),
        hotkey: None,
        operation_title: Some("Set the free-run tempo"),
        action: Some("Click or Drag"),
        mcp_policy: Some("set_tempo"),
    },
    ControlDescriptor {
        id: ControlId::MixerStrip,
        probe_name: ControlId::MixerStrip.probe_name(),
        eyebrow: "MIXER",
        label: "Mixer strip",
        summary: Some("Channel strip fader, solo, mute, and deck selection"),
        hotkey: None,
        operation_title: Some("Select a deck"),
        action: Some("Click to select"),
        mcp_policy: Some("select_deck"),
    },
    ControlDescriptor {
        id: ControlId::Transition,
        probe_name: ControlId::Transition.probe_name(),
        eyebrow: "MIXER",
        label: "Transition row",
        summary: Some("Crossfader, transition geometry, and auto-wipe trigger"),
        hotkey: Some("space"),
        operation_title: Some("Wipe the next deck in"),
        action: Some("Click to wipe"),
        mcp_policy: Some("transition"),
    },
    ControlDescriptor {
        id: ControlId::Master,
        probe_name: ControlId::Master.probe_name(),
        eyebrow: "MASTER",
        label: "Master bay",
        summary: Some("Master output attenuation and master FX chain slots"),
        hotkey: None,
        operation_title: Some("Master out"),
        action: Some("Drag fader"),
        mcp_policy: Some("set_master"),
    },
    ControlDescriptor {
        id: ControlId::InspectorPaneName,
        probe_name: ControlId::InspectorPaneName.probe_name(),
        eyebrow: "INSPECTOR",
        label: "Inspector pane name",
        summary: Some("Rename active Set in the selected deck"),
        hotkey: None,
        operation_title: None,
        action: Some("Click to rename"),
        mcp_policy: Some("rename_set"),
    },
    ControlDescriptor {
        id: ControlId::InspectorPaneKeep,
        probe_name: ControlId::InspectorPaneKeep.probe_name(),
        eyebrow: "INSPECTOR",
        label: "Inspector pane keep capsule",
        summary: Some("Snapshot and save active deck Set to store"),
        hotkey: Some("k"),
        operation_title: Some("Keep what a deck is playing"),
        action: Some("Click to save"),
        mcp_policy: Some("keep_deck"),
    },
    ControlDescriptor {
        id: ControlId::InspectorSlotMcp,
        probe_name: ControlId::InspectorSlotMcp.probe_name(),
        eyebrow: "INSPECTOR",
        label: "Inspector pane slot MCP policy",
        summary: Some("Agent mutation policy for this deck slot"),
        hotkey: None,
        operation_title: None,
        action: Some("Click to toggle"),
        mcp_policy: Some("set_slot_mcp_policy"),
    },
    ControlDescriptor {
        id: ControlId::InspectorPaneTarget,
        probe_name: ControlId::InspectorPaneTarget.probe_name(),
        eyebrow: "INSPECTOR",
        label: "Inspector pane deck pulldown",
        summary: Some("Select which deck this Inspector pane displays"),
        hotkey: None,
        operation_title: Some("Point an Inspector pane at a deck"),
        action: Some("Click to switch"),
        mcp_policy: Some("target_deck"),
    },
    ControlDescriptor {
        id: ControlId::InspectorDeckHead,
        probe_name: ControlId::InspectorDeckHead.probe_name(),
        eyebrow: "INSPECTOR",
        label: "Deck head controls",
        summary: Some("Deck sync mode and transport phase alignment"),
        hotkey: None,
        operation_title: Some("Set a deck's sync mode"),
        action: Some("Click to cycle"),
        mcp_policy: Some("set_sync"),
    },
    ControlDescriptor {
        id: ControlId::InspectorRenderers,
        probe_name: ControlId::InspectorRenderers.probe_name(),
        eyebrow: "INSPECTOR",
        label: "Renderer chips",
        summary: Some("Select active base renderer procedure"),
        hotkey: None,
        operation_title: Some("Choose which renderer of a deck is live"),
        action: Some("Click to choose"),
        mcp_policy: Some("choose_renderer"),
    },
    ControlDescriptor {
        id: ControlId::InspectorParam,
        probe_name: ControlId::InspectorParam.probe_name(),
        eyebrow: "INSPECTOR",
        label: "Parameter row fader",
        summary: Some("Adjust published procedural parameter value"),
        hotkey: None,
        operation_title: Some("Write a parameter"),
        action: Some("Drag fader"),
        mcp_policy: Some("set_param"),
    },
    ControlDescriptor {
        id: ControlId::InspectorPublish,
        probe_name: ControlId::InspectorPublish.probe_name(),
        eyebrow: "INSPECTOR",
        label: "Parameter row publish mark",
        summary: Some("Toggle publication mark on mixer interface"),
        hotkey: None,
        operation_title: Some("Narrow the published interface"),
        action: Some("Click to toggle"),
        mcp_policy: Some("publish_param"),
    },
    ControlDescriptor {
        id: ControlId::InspectorUses,
        probe_name: ControlId::InspectorUses.probe_name(),
        eyebrow: "INSPECTOR",
        label: "Node uses capsule and card",
        summary: Some("Inspect procedure input dependency wiring"),
        hotkey: None,
        operation_title: Some("Wire a procedure's input to a node"),
        action: Some("Click to wire"),
        mcp_policy: Some("wire_input"),
    },
    ControlDescriptor {
        id: ControlId::InspectorAuthority,
        probe_name: ControlId::InspectorAuthority.probe_name(),
        eyebrow: "INSPECTOR",
        label: "Node authority chips",
        summary: Some("Control arbitration authority for this node"),
        hotkey: None,
        operation_title: Some("Set a node's authority"),
        action: Some("Click to set"),
        mcp_policy: Some("set_authority"),
    },
    ControlDescriptor {
        id: ControlId::InspectorNodeKeep,
        probe_name: ControlId::InspectorNodeKeep.probe_name(),
        eyebrow: "INSPECTOR",
        label: "Node keep capsule",
        summary: Some("Save individual node procedure to library"),
        hotkey: None,
        operation_title: Some("Keep a node's procedure"),
        action: Some("Click to save"),
        mcp_policy: Some("keep_node"),
    },
    ControlDescriptor {
        id: ControlId::InspectorSensitivity,
        probe_name: ControlId::InspectorSensitivity.probe_name(),
        eyebrow: "INSPECTOR",
        label: "Sensitivity curve and take back",
        summary: Some("Input sensitivity curve and parameter take-back"),
        hotkey: None,
        operation_title: Some("Take a parameter back"),
        action: Some("Click or Drag"),
        mcp_policy: Some("take_param_back"),
    },
    ControlDescriptor {
        id: ControlId::ProgramSolo,
        probe_name: ControlId::ProgramSolo.probe_name(),
        eyebrow: "PROGRAM",
        label: "Program bay solo capsule",
        summary: Some("Toggle borderless fullscreen program view"),
        hotkey: None,
        operation_title: Some("Solo the program view"),
        action: Some("Click to solo"),
        mcp_policy: Some("solo_program"),
    },
    ControlDescriptor {
        id: ControlId::BayGrip,
        probe_name: ControlId::BayGrip.probe_name(),
        eyebrow: "CONSOLE",
        label: "Bay head fold grip",
        summary: Some("Fold or expand console workspace bay"),
        hotkey: Some("g"),
        operation_title: Some("Fold a pane away"),
        action: Some("Click to fold"),
        mcp_policy: None,
    },
    ControlDescriptor {
        id: ControlId::DeckPreview,
        probe_name: ControlId::DeckPreview.probe_name(),
        eyebrow: "PROGRAM",
        label: "Deck preview cells",
        summary: Some("Select deck and monitor pre-fader video signal"),
        hotkey: None,
        operation_title: Some("Select a deck"),
        action: Some("Click to select"),
        mcp_policy: Some("select_deck"),
    },
    ControlDescriptor {
        id: ControlId::LibraryScope,
        probe_name: ControlId::LibraryScope.probe_name(),
        eyebrow: "LIBRARY",
        label: "Library scope chips",
        summary: Some("Filter library items by scope and directory"),
        hotkey: None,
        operation_title: Some("Choose which scope the library shows"),
        action: Some("Click to choose"),
        mcp_policy: Some("list_library"),
    },
    ControlDescriptor {
        id: ControlId::LibraryFilter,
        probe_name: ControlId::LibraryFilter.probe_name(),
        eyebrow: "LIBRARY",
        label: "Library filter fields",
        summary: Some("Filter library items by node name or text query"),
        hotkey: None,
        operation_title: Some("Filter the library"),
        action: Some("Type to filter"),
        mcp_policy: Some("filter_library"),
    },
    ControlDescriptor {
        id: ControlId::LibraryKinds,
        probe_name: ControlId::LibraryKinds.probe_name(),
        eyebrow: "LIBRARY",
        label: "Library kind chips",
        summary: Some("Filter library items by procedure kind"),
        hotkey: None,
        operation_title: Some("Filter the library by kind"),
        action: Some("Click to filter"),
        mcp_policy: Some("filter_library_kind"),
    },
    ControlDescriptor {
        id: ControlId::LibraryBadges,
        probe_name: ControlId::LibraryBadges.probe_name(),
        eyebrow: "LIBRARY",
        label: "Library row badges",
        summary: Some("Display procedure kind badges for library item"),
        hotkey: None,
        operation_title: None,
        action: Some("Click to view"),
        mcp_policy: None,
    },
    ControlDescriptor {
        id: ControlId::LibraryParams,
        probe_name: ControlId::LibraryParams.probe_name(),
        eyebrow: "LIBRARY",
        label: "Library params chip",
        summary: Some("Toggle display of declared Set parameters"),
        hotkey: None,
        operation_title: Some("Read what one Set holds and declares"),
        action: Some("Click to inspect"),
        mcp_policy: Some("inspect_set"),
    },
    ControlDescriptor {
        id: ControlId::LibraryLoad,
        probe_name: ControlId::LibraryLoad.probe_name(),
        eyebrow: "LIBRARY",
        label: "Library load button and deck pulldown",
        summary: Some("Load selected Set into target deck"),
        hotkey: Some("enter"),
        operation_title: Some("Load material into a deck"),
        action: Some("Click or Drop"),
        mcp_policy: Some("load_deck"),
    },
    ControlDescriptor {
        id: ControlId::LibraryStars,
        probe_name: ControlId::LibraryStars.probe_name(),
        eyebrow: "LIBRARY",
        label: "Library row stars",
        summary: Some("Toggle favourite star marker on library Set"),
        hotkey: None,
        operation_title: Some("Star a Set, or take the star off"),
        action: Some("Click to star"),
        mcp_policy: Some("star_set"),
    },
    ControlDescriptor {
        id: ControlId::LibraryList,
        probe_name: ControlId::LibraryList.probe_name(),
        eyebrow: "LIBRARY",
        label: "Library list rows",
        summary: Some("Browse available Sets and procedures in store"),
        hotkey: None,
        operation_title: Some("List what the store holds"),
        action: Some("Click or Drag"),
        mcp_policy: Some("list_library"),
    },
    ControlDescriptor {
        id: ControlId::ClassPills,
        probe_name: ControlId::ClassPills.probe_name(),
        eyebrow: "SECURITY",
        label: "MCP safety class pills",
        summary: Some("Configure agent safety class execution gates"),
        hotkey: None,
        operation_title: None,
        action: Some("Click to cycle"),
        mcp_policy: Some("set_class_policy"),
    },
    ControlDescriptor {
        id: ControlId::Sequencer,
        probe_name: ControlId::Sequencer.probe_name(),
        eyebrow: "SEQUENCER",
        label: "Sequencer bay controls, including a lane's minus",
        summary: Some("Pattern step grid triggering parameter automation"),
        hotkey: None,
        operation_title: Some("Toggle a step"),
        action: Some("Click to toggle"),
        mcp_policy: Some("toggle_step"),
    },
    ControlDescriptor {
        id: ControlId::StagingBack,
        probe_name: ControlId::StagingBack.probe_name(),
        eyebrow: "STAGING",
        label: "Staging lane back capsules",
        summary: Some("Discard unpromoted shader candidate"),
        hotkey: None,
        operation_title: Some("Take a candidate back"),
        action: Some("Click to return"),
        mcp_policy: Some("return_candidate"),
    },
    ControlDescriptor {
        id: ControlId::StagingCandidate,
        probe_name: ControlId::StagingCandidate.probe_name(),
        eyebrow: "STAGING",
        label: "Staging lane candidate rows",
        summary: Some("Promote candidate shader build into live deck"),
        hotkey: None,
        operation_title: Some("Promote a candidate"),
        action: Some("Click to promote"),
        mcp_policy: Some("promote_candidate"),
    },
];

/// Query helper returning the descriptor for a strongly-typed [`ControlId`].
pub fn descriptor_for(id: ControlId) -> &'static ControlDescriptor {
    &DESCRIPTORS[id.probe_index()]
}

/// Query helper returning the descriptor matching a probe name string, if any.
pub fn descriptor_for_probe(probe_name: &str) -> Option<&'static ControlDescriptor> {
    DESCRIPTORS.iter().find(|d| d.probe_name == probe_name)
}

/// Query helper returning the descriptor matching a keyboard shortcut, if any.
pub fn descriptor_for_hotkey(hotkey: &str) -> Option<&'static ControlDescriptor> {
    DESCRIPTORS.iter().find(|d| d.hotkey == Some(hotkey))
}
